package com.github.swent.echo.data.repository

import com.github.swent.echo.data.model.Association
import com.github.swent.echo.data.model.Event
import com.github.swent.echo.data.model.Tag
import com.github.swent.echo.data.model.UserProfile

interface Repository {

    companion object {
        /** The root tag of the tag tree. Note the sub-tags of this tag are the top-level tags. */
        const val ROOT_TAG_ID = "1d253a7e-eb8c-4546-bc98-1d3adadcffe8"
    }

    suspend fun getAssociation(associationId: String): Association

    suspend fun getAllAssociations(): List<Association>

    suspend fun getEvent(eventId: String): Event

    /**
     * Creates a new event. The [Event.eventId] will be generated by the server and returned.
     *
     * @param event The id of the created event.
     */
    suspend fun createEvent(event: Event): String

    suspend fun setEvent(event: Event)

    suspend fun getAllEvents(): List<Event>

    suspend fun getTag(tagId: String): Tag

    /**
     * Get all sub-tags of a given tag.
     *
     * @param tagId The id of the tag.
     * @return The list of sub-tags.
     */
    suspend fun getSubTags(tagId: String): List<Tag> {
        return emptyList()
    }

    suspend fun getAllTags(): List<Tag>

    /**
     * Gets the profile of a user. If the user does not exist, returns null.
     *
     * @param userId The id of the user.
     * @return The profile of the user or null if the user has no profile associated.
     */
    suspend fun getUserProfile(userId: String): UserProfile?

    suspend fun setUserProfile(userProfile: UserProfile)
}
