package com.github.swent.echo.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006A66)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF7CEAE3)
val onPrimaryContainerLight = Color(0xFF004A47)
val secondaryLight = Color(0xFF3F6562)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC3ECE8)
val onSecondaryContainerLight = Color(0xFF294F4D)
val tertiaryLight = Color(0xFF625885)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDDD1FF)
val onTertiaryContainerLight = Color(0xFF443B66)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FAF9)
val onBackgroundLight = Color(0xFF171D1C)
val surfaceLight = Color(0xFFF5FAF9)
val onSurfaceLight = Color(0xFF171D1C)
val surfaceVariantLight = Color(0xFFD8E5E3)
val onSurfaceVariantLight = Color(0xFF3D4948)
val outlineLight = Color(0xFF6D7A78)
val outlineVariantLight = Color(0xFFBCC9C7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3131)
val inverseOnSurfaceLight = Color(0xFFEDF2F0)
val inversePrimaryLight = Color(0xFF69D8D1)
val surfaceDimLight = Color(0xFFD6DBDA)
val surfaceBrightLight = Color(0xFFF5FAF9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5F3)
val surfaceContainerLight = Color(0xFFEAEFED)
val surfaceContainerHighLight = Color(0xFFE4E9E8)
val surfaceContainerHighestLight = Color(0xFFDEE4E2)

val primaryDark = Color(0xFFD5FFFB)
val onPrimaryDark = Color(0xFF003735)
val primaryContainerDark = Color(0xFF6FDED7)
val onPrimaryContainerDark = Color(0xFF00423F)
val secondaryDark = Color(0xFFA6CECB)
val onSecondaryDark = Color(0xFF0D3634)
val secondaryContainerDark = Color(0xFF1E4543)
val onSecondaryContainerDark = Color(0xFFB3DBD8)
val tertiaryDark = Color(0xFFFCF6FF)
val onTertiaryDark = Color(0xFF332A54)
val tertiaryContainerDark = Color(0xFFD3C6FB)
val onTertiaryContainerDark = Color(0xFF3E345F)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1414)
val onBackgroundDark = Color(0xFFDEE4E2)
val surfaceDark = Color(0xFF0F1414)
val onSurfaceDark = Color(0xFFDEE4E2)
val surfaceVariantDark = Color(0xFF3D4948)
val onSurfaceVariantDark = Color(0xFFBCC9C7)
val outlineDark = Color(0xFF879392)
val outlineVariantDark = Color(0xFF3D4948)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4E2)
val inverseOnSurfaceDark = Color(0xFF2C3131)
val inversePrimaryDark = Color(0xFF006A66)
val surfaceDimDark = Color(0xFF0F1414)
val surfaceBrightDark = Color(0xFF353A3A)
val surfaceContainerLowestDark = Color(0xFF0A0F0F)
val surfaceContainerLowDark = Color(0xFF171D1C)
val surfaceContainerDark = Color(0xFF1B2120)
val surfaceContainerHighDark = Color(0xFF262B2A)
val surfaceContainerHighestDark = Color(0xFF303635)






